//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by SystemTool.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_SYSTEMTOOL                  3
#define IDI_SYSTEMTOOL                  101
#define IDM_MENU                        102
#define IDD_ABOUTBOX                    103
#define IDD_CPUBOX                      104
#define IDI_ICON_UNKNOW                 104
#define IDI_ICON2                       105
#define IDD_TOOLHELPBOX                 105
#define IDI_ICON3                       106
#define IDD_OSBENCHBOX                  106
#define IDI_ICON4                       107
#define IDD_SYSPOWERBOX                 107
#define IDI_ICON5                       108
#define IDD_CUNITBOX                    108
#define IDI_ICON6                       109
#define IDD_IPCBOX                      109
#define IDI_ICON7                       110
#define IDD_WINOVERLAYBOX               110
#define IDI_ICON8                       111
#define IDI_ICON9                       112
#define IDI_ICON10                      113
#define IDI_ICON11                      114
#define IDI_ICON12                      115
#define IDI_ICON13                      116
#define IDI_ICON14                      117
#define IDI_ICON15                      118
#define IDI_ICON16                      119
#define IDI_ICON17                      120
#define IDI_ICON18                      121
#define IDI_ICON19                      122
#define IDI_ICON00                      123
#define IDI_ICON05                      124
#define IDI_ICON06                      125
#define IDI_ICON07                      126
#define IDI_ICON08                      127
#define IDI_ICON09                      128
#define IDI_ICON100                     129
#define IDI_ICON20                      130
#define IDI_ICON25                      131
#define IDI_ICON30                      132
#define IDI_ICON35                      133
#define IDI_ICON40                      134
#define IDI_ICON45                      135
#define IDI_ICON55                      136
#define IDI_ICON60                      137
#define IDI_ICON65                      138
#define IDI_ICON1                       139
#define IDI_ICON21                      140
#define IDI_ICON22                      141
#define IDI_ICON23                      142
#define IDI_ICON24                      143
#define IDI_ICON26                      144
#define IDI_ICON27                      145
#define IDI_ICON28                      146
#define IDI_ICON29                      147
#define IDI_ICON31                      148
#define IDI_ICON32                      149
#define IDI_ICON33                      150
#define IDI_ICON34                      151
#define IDI_ICON36                      152
#define IDI_ICON37                      153
#define IDI_ICON70                      154
#define IDI_ICON75                      155
#define IDI_ICON80                      156
#define IDI_ICON85                      157
#define IDI_ICON90                      158
#define IDI_ICON91                      159
#define IDI_ICON92                      160
#define IDI_ICON93                      161
#define IDI_ICON94                      162
#define IDI_ICON95                      163
#define IDI_ICON96                      164
#define IDI_ICON97                      165
#define IDI_ICON98                      166
#define IDI_ICON99                      167
#define IDI_ICON_SYSTEMTRAY             168
#define IDC_CPU_CHECK_EXIT2TAY          1001
#define IDC_CPU_PROGRESS1               1002
#define IDC_CPU_STATIC2                 1003
#define IDC_CPU_PROGRESS2               1004
#define IDC_CPU_CLS                     1005
#define IDC_CPU_LIST1                   1006
#define IDC_CPU_STATIC3                 1007
#define IDC_TOOLHELP_STATIC1            1008
#define IDC_TOOLHELP_STATIC2            1009
#define IDC_TOOLHELP_LIST1              1010
#define IDC_TOOLHELP_CLS                1011
#define IDC_TOOLHELP_SNAPSHOT           1012
#define IDC_TOOLHELP_SNAPSHOT2          1013
#define IDC_TOOLHELP_SNAPSHOT3          1014
#define IDC_TOOLHELP_STATIC3            1015
#define IDC_OSBENCH_STATIC2             1017
#define IDC_OSBENCH_CLS                 1019
#define IDC_OSBENCH_LIST1               1020
#define IDC_OSBENCH_OSBENCH             1021
#define IDC_SYSPOWER_LIST1              1021
#define IDC_OSBENCH_ILTIMING            1022
#define IDC_SYSPOWER_STATIC1            1022
#define IDC_SYSPOWER_SNAPSHOT           1023
#define IDC_SYSPOWER_SET                1023
#define IDC_OSBENCH_DISPPERF            1024
#define IDC_SYSPOWER_STATIC2            1024
#define IDC_SYSPOWER_SNAPSHOT2          1025
#define IDC_SYSPOWER_RELEASE            1025
#define IDC_SYSPOWER_STATIC3            1026
#define IDC_SYSPOWER_SNAPSHOT3          1027
#define IDC_SYSPOWER_NONE               1027
#define IDC_SYSPOWER_CLS                1028
#define IDC_CUNIT_LIST1                 1029
#define IDC_CUNIT_RUN                   1030
#define IDC_CUNIT_CLS                   1031
#define IDC_CUNIT_RUN2                  1032
#define IDC_CUNIT_PROGRESS1             1033
#define IDC_CUNIT_RUN3                  1034
#define IDC_IPC_LIST1                   1034
#define IDC_CUNIT_RUN4                  1035
#define IDC_IPC_LIST2                   1035
#define IDC_IPC_STATIC1                 1036
#define IDC_IPC_INITHOST                1037
#define IDC_IPC_STATIC2                 1038
#define IDC_IPC_CLIENTINIT              1039
#define IDC_IPC_CLS                     1040
#define IDC_WINOVERLAY_LIST1            1041
#define IDC_WINOVERLAY_SET              1042
#define IDC_WINOVERLAY_ALPHA            1042
#define IDC_WINOVERLAY_RELEASE          1043
#define IDC_WINOVERLAY_KEY              1043
#define IDC_WINOVERLAY_RUN              1044
#define IDC_WINOVERLAY_CLS              1045
#define IDM_FILE_EXIT                   40002
#define IDM_HELP_ABOUT                  40003
#define IDM_OPTION_MINIMIZE             40004
#define IDM_ITEMS_CPU_USEAGE            40005
#define IDM_ITEMS_TOOLHELP              40006
#define IDM_OSBENCH_ALL                 40007
#define IDM_GDI_TEST                    40008
#define IDM_CUNIT_TEST                  40009
#define IDM_SYSPOWER_TEST               40010
#define IDM_IPC_TEST                    40011
#define IDM_WINOVERLAY_TEST             40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
