/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Reno_Icon_20_GPS_Lock
* Dimensions:  20 * 20
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsReno_Icon_20_GPS_Lock[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalReno_Icon_20_GPS_Lock = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsReno_Icon_20_GPS_Lock[0]
};

static GUI_CONST_STORAGE unsigned char acReno_Icon_20_GPS_Lock[] = {
  XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXX___, XXXX____,
  XXXXXXXX, XXXX____, _XXX____,
  XXXXXXXX, XXX_____, __XX____,
  XXXXXXXX, XXX_____, ___X____,
  XXXXXXXX, XXX_____, __XX____,
  XXXXXXXX, XXX_____, _XXX____,
  XXXXXXX_, ________, XXXX____,
  XXXXXXX_, ____XXXX, XXXX____,
  XXXXXXX_, ____XXXX, XXXX____,
  XXXXXXX_, ____XXXX, XXXX____,
  XXX_____, ____XXXX, XXXX____,
  XX______, XXXXXXXX, XXXX____,
  X_______, XXXXXXXX, XXXX____,
  X_______, XXXXXXXX, XXXX____,
  X_______, XXXXXXXX, XXXX____,
  XX_____X, XXXXXXXX, XXXX____,
  XXX___XX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXX____
};

GUI_CONST_STORAGE GUI_BITMAP bmReno_Icon_20_GPS_Lock = {
  20, /* XSize */
  20, /* YSize */
  3, /* BytesPerLine */
  1, /* BitsPerPixel */
  acReno_Icon_20_GPS_Lock,  /* Pointer to picture data (indices) */
  &PalReno_Icon_20_GPS_Lock  /* Pointer to palette */
};

/* *** End of file *** */
