/**************************************************************
 * HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 **************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP Stack/TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_CONN curHTTP;
extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern BYTE curHTTPID;

void HTTPPrint(DWORD callbackID);
void HTTPPrint_builddate(void);
void HTTPPrint_version(void);
void HTTPPrint_electric_units(void);
void HTTPPrint_electric_total(void);
void HTTPPrint_electric_cost(void);
void HTTPPrint_electric_onoff(void);
void HTTPPrint_gas_units(void);
void HTTPPrint_gas_total(void);
void HTTPPrint_gas_cost(void);
void HTTPPrint_gas_onoff(void);
void HTTPPrint_temperature(void);
void HTTPPrint_setpoint(void);
void HTTPPrint_pot(void);
void HTTPPrint_electric(void);
void HTTPPrint_config_mac(void);
void HTTPPrint_config_hostname(void);
void HTTPPrint_config_dhcpchecked(void);
void HTTPPrint_config_ip(void);
void HTTPPrint_config_gw(void);
void HTTPPrint_config_subnet(void);
void HTTPPrint_config_dns1(void);
void HTTPPrint_config_dns2(void);

void HTTPPrint(DWORD callbackID)
{
	switch(callbackID)
	{
        case 0x00000000:
			HTTPPrint_builddate();
			break;
        case 0x00000001:
			HTTPPrint_version();
			break;
        case 0x00000002:
			HTTPPrint_electric_units();
			break;
        case 0x00000003:
			HTTPPrint_electric_total();
			break;
        case 0x00000004:
			HTTPPrint_electric_cost();
			break;
        case 0x00000005:
			HTTPPrint_electric_onoff();
			break;
        case 0x00000006:
			HTTPPrint_gas_units();
			break;
        case 0x00000007:
			HTTPPrint_gas_total();
			break;
        case 0x00000008:
			HTTPPrint_gas_cost();
			break;
        case 0x00000009:
			HTTPPrint_gas_onoff();
			break;
        case 0x0000000a:
			HTTPPrint_temperature();
			break;
        case 0x0000000b:
			HTTPPrint_setpoint();
			break;
        case 0x0000000c:
			HTTPPrint_pot();
			break;
        case 0x0000000d:
			HTTPPrint_electric();
			break;
        case 0x0000000e:
			HTTPPrint_config_mac();
			break;
        case 0x0000000f:
			HTTPPrint_config_hostname();
			break;
        case 0x00000010:
			HTTPPrint_config_dhcpchecked();
			break;
        case 0x00000011:
			HTTPPrint_config_ip();
			break;
        case 0x00000012:
			HTTPPrint_config_gw();
			break;
        case 0x00000013:
			HTTPPrint_config_subnet();
			break;
        case 0x00000014:
			HTTPPrint_config_dns1();
			break;
        case 0x00000015:
			HTTPPrint_config_dns2();
			break;
		default:
			// Output notification for undefined values
			TCPPutROMArray(sktHTTP, (ROM BYTE*)"!DEF", 4);
	}

	return;
}

void HTTPPrint_(void)
{
	TCPPut(sktHTTP, '~');
	return;
}

#endif

#endif
