//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by ReserveFlash.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_RESERVEFLASH                3
#define IDI_RESERVEFLASH                101
#define IDM_MENU                        102
#define IDD_ABOUTBOX                    103
#define IDD_HWVERSIONBOX                104
#define IDD_FLASHCONTENTBOX             105
#define IDD_TOUCHBOX                    106
#define IDD_BACKLIGHTBOX                107
#define IDD_HARDDRIVEBOX                108
#define IDD_GPSBOX                      109
#define IDD_VDBGBOX                     110
#define IDD_SDMMCBOX                    111
#define IDD_ECHOBOX                     112
#define IDD_PERFCOUNTBOX                113
#define IDD_AUDIOBOX                    114
#define IDD_VOLUMEBOX                   115
#define IDD_EQBOX                       116
#define IDD_SWVOLUMEBOX                 117
#define IDD_BTBOX                       118
#define IDD_AVBOX                       119
#define IDC_HWVERSION_COMBO             1002
#define IDC_HWVERSION_READ              1003
#define IDC_HWVERSION_EDIT              1004
#define IDC_HWVERSION_WRITE             1005
#define IDC_STATIC_ID                   1005
#define IDC_STATIC_NAME                 1006
#define IDC_CURRDRIVER_EDIT             1006
#define IDC_STATIC_DATA                 1007
#define IDC_SERIALNUMBER_EDIT           1007
#define IDC_EDIT_ID                     1008
#define IDC_SERIALNUMBER_READ           1008
#define IDC_EDIT_NAME                   1009
#define IDC_SERIALNUMBER_WRITE          1009
#define IDC_EDIT_DATA                   1010
#define IDC_SERIALNUMBER_COMBO1         1010
#define IDC_FLASHCONTENT_UP             1011
#define IDC_SERIALNUMBER_COMBO2         1011
#define IDC_FLASHCONTENT_DOWN           1012
#define IDC_SERIALNUMBER_COMBO3         1012
#define IDC_EDIT_TATALRECORD            1013
#define IDC_SERIALNUMBER_COMBO4         1013
#define IDC_FLASHCONTENT_LOAD           1014
#define IDC_STATIC_BATTERYLOAD          1014
#define IDC_FLASHCONTENT_FLASH          1015
#define IDC_RADIO_A1                    1015
#define IDC_SERIALNUMBER_COMBO5         1015
#define IDC_RADIO_A2                    1016
#define IDC_BACKLIGHT_AUTO              1016
#define IDC_SERIALNUMBER_COMBO6         1016
#define IDC_RADIO_A3                    1017
#define IDC_STATIC_BACKLIGHT            1017
#define IDC_SERIALNUMBER_COMBO7         1017
#define IDC_FLASHCONTENT_FLUSH          1018
#define IDC_RADIO_A4                    1018
#define IDC_BACKLIGHT_AUTO2             1018
#define IDC_SERIALNUMBER_COMBO8         1018
#define IDC_FLASHCONTENT_DELETE         1019
#define IDC_RADIO_B1                    1019
#define IDC_STATIC_BACKLIGHT2           1019
#define IDC_RADIO_B2                    1020
#define IDC_BACKLIGHT_PROGRESS          1020
#define IDC_RADIO_B3                    1021
#define IDC_HDD_TEST                    1021
#define IDC_HDD_AUTO_TEST               1021
#define IDC_STATIC_BACKLIGHT3           1021
#define IDC_RADIO_B4                    1022
#define IDC_HDD_EDIT1                   1022
#define IDC_BACKLIGHT_DOWN              1022
#define IDC_RADIO_C1                    1023
#define IDC_HDD_WRITE                   1023
#define IDC_BACKLIGHT_DOWN2             1023
#define IDC_RADIO_C2                    1024
#define IDC_HDD_READ                    1024
#define IDC_BACKLIGHT_UP                1024
#define IDC_RADIO_C3                    1025
#define IDC_HDD_CLS                     1025
#define IDC_BACKLIGHT_UP2               1025
#define IDC_RADIO_C4                    1026
#define IDC_HDD_LIST1                   1026
#define IDC_BACKLIGHT_SET               1026
#define IDC_RADIO_D1                    1027
#define IDC_HDD_COPY                    1027
#define IDC_GPS_LIST1                   1027
#define IDC_RADIO_D2                    1028
#define IDC_GPS_CLS                     1028
#define IDC_HDD_OFF                     1028
#define IDC_RADIO_D3                    1029
#define IDC_GPS_PAUSE                   1029
#define IDC_HDD_READ_IO                 1029
#define IDC_RADIO_D4                    1030
#define IDC_GPS_PORT_COMBO              1030
#define IDC_HDD_ON                      1030
#define IDC_GPS_BAUD_COMBO              1031
#define IDC_GPS_STOP                    1032
#define IDC_GPS_START                   1033
#define IDC_VDBG_LIST1                  1034
#define IDC_VDBG_PORT_COMBO             1035
#define IDC_VDBG_BAUD_COMBO             1036
#define IDC_VDBG_START                  1037
#define IDC_VDBG_STOP                   1038
#define IDC_VDBG_PAUSE                  1039
#define IDC_VDBG_CLS                    1040
#define IDC_CHECK_CHANGE_GO             1041
#define IDC_SDMMC_EDIT1                 1042
#define IDC_SDMMC_COPY                  1043
#define IDC_SDMMC_CLS                   1044
#define IDC_SDMMC_READ                  1045
#define IDC_SDMMC_WRITE                 1046
#define IDC_SDMMC_AUTO_TEST             1047
#define IDC_SDMMC_OFF                   1048
#define IDC_SDMMC_ON                    1049
#define IDC_SDMMC_LIST1                 1050
#define IDC_WRITEFILE_CHECK             1051
#define IDC_READFILE_CHECK              1052
#define IDC_ECHO_LIST1                  1052
#define IDC_READIO_CHECK                1053
#define IDC_ECHO_EDIT1                  1053
#define IDC_COPYFILE_CHECK              1054
#define IDC_ECHO_IOCTL_PRESET1          1054
#define IDC_HDD_AUTOSUSPEND_CHECK       1055
#define IDC_ECHO_IOCTL_PRESET2          1055
#define IDC_ECHO_EVENT_PRESET1          1056
#define IDC_ECHO_EVENT_PRESET2          1057
#define IDC_ECHO_IOCTL_BYPASS           1058
#define IDC_ECHO_EVENT_BYPASS           1059
#define IDC_ECHO_IOCTL_POWERDOWN        1060
#define IDC_ECHO_EVENT_POWERDOWN        1061
#define IDC_ECHO_CLS                    1062
#define IDC_PERFCOUNT_BUTTON1           1063
#define IDC_ECHO_CHECK                  1063
#define IDC_PERFCOUNT_BUTTON2           1064
#define IDC_PERFCOUNT_BUTTON3           1065
#define IDC_PERFCOUNT_BUTTON4           1066
#define IDC_PERFCOUNT_BUTTON5           1067
#define IDC_PERFCOUNT_BUTTON6           1068
#define IDC_PERFCOUNT_BUTTON7           1069
#define IDC_PERFCOUNT_CHECK             1070
#define IDC_PERFCOUNT_CLS               1071
#define IDC_PERFCOUNT_EDIT1             1072
#define IDC_PERFCOUNT_LIST1             1073
#define IDC_AUDIO_LIST1                 1074
#define IDC_AUDIO_EDIT1                 1075
#define IDC_AUDIO_CLS                   1079
#define IDC_AUDIO_WRITE                 1080
#define IDC_AUDIO_READ                  1081
#define IDC_AUDIO_DIFF_B                1082
#define IDC_AUDIO_BUTTON2               1083
#define IDC_AUDIO_DIFF_A                1083
#define IDC_AUDIO_DUMP                  1084
#define IDC_AUDIO_ADDR_COMBO1           1085
#define IDC_AUDIO_ADDR_COMBO2           1086
#define IDC_AUDIO_VALUE_COMBO1          1087
#define IDC_AUDIO_VALUE_COMBO2          1088
#define IDC_AUDIO_STATIC2               1089
#define IDC_AUDIO_VALUE_COMBO3          1090
#define IDC_AUDIO_VALUE_COMBO4          1091
#define IDC_AUDIO_STATIC3               1092
#define IDC_AUDIO_STATIC1               1092
#define IDC_AUDIO_CHECK15               1093
#define IDC_AUDIO_CHECK14               1094
#define IDC_VOLUME_CHECK2               1094
#define IDC_AUDIO_CHECK13               1095
#define IDC_VOLUME_CHECK3               1095
#define IDC_AUDIO_CHECK12               1096
#define IDC_VOLUME_CHECK4               1096
#define IDC_AUDIO_CHECK11               1097
#define IDC_VOLUME_CHECK5               1097
#define IDC_AUDIO_CHECK10               1098
#define IDC_VOLUME_CHECK6               1098
#define IDC_AUDIO_CHECK9                1099
#define IDC_VOLUME_CHECK7               1099
#define IDC_AUDIO_CHECK8                1100
#define IDC_VOLUME_CHECK8               1100
#define IDC_AUDIO_CHECK7                1101
#define IDC_VOLUME_CHECK9               1101
#define IDC_AUDIO_CHECK6                1102
#define IDC_AUDIO_CHECK5                1103
#define IDC_AUDIO_CHECK4                1104
#define IDC_AUDIO_CHECK3                1105
#define IDC_AUDIO_CHECK2                1106
#define IDC_AUDIO_CHECK1                1107
#define IDC_AUDIO_CHECK0                1108
#define IDC_AUDIO_STATIC4               1109
#define IDC_VOLUME_SLIDER1              1110
#define IDC_AUDIO_W2FILE                1110
#define IDC_VOLUME_SLIDER2              1111
#define IDC_VOLUME_STATIC1              1112
#define IDC_VOLUME_EDIT1                1114
#define IDC_VOLUME_STATIC2              1117
#define IDC_VOLUME_EDIT2                1118
#define IDC_VOLUME_CHECK1               1119
#define IDC_VOLUME_STATIC3              1120
#define IDC_EQ_LIST1                    1120
#define IDC_VOLUME_SLIDER3              1121
#define IDC_EQ_EDIT1                    1121
#define IDC_VOLUME_EDIT3                1122
#define IDC_EQ_CLS                      1122
#define IDC_VOLUME_STATIC4              1123
#define IDC_EQ_DUMP                     1123
#define IDC_VOLUME_SLIDER4              1124
#define IDC_EQ_STATIC1                  1124
#define IDC_VOLUME_EDIT4                1125
#define IDC_EQ_WRITE                    1125
#define IDC_VOLUME_STATIC5              1126
#define IDC_EQ_READ                     1126
#define IDC_VOLUME_SLIDER5              1127
#define IDC_EQ_COMBO1                   1127
#define IDC_VOLUME_EDIT5                1128
#define IDC_EQ_CHECK_DEVICE             1128
#define IDC_SWVOLUME_STATIC1            1128
#define IDC_VOLUME_STATIC6              1129
#define IDC_SWVOLUME_SLIDER1            1129
#define IDC_VOLUME_SLIDER6              1130
#define IDC_SWVOLUME_CHECK1             1130
#define IDC_VOLUME_EDIT6                1131
#define IDC_SWVOLUME_EDIT1              1131
#define IDC_VOLUME_STATIC7              1132
#define IDC_SWVOLUME_PLAY               1132
#define IDC_VOLUME_SLIDER7              1133
#define IDC_SWVOLUME_STOP               1133
#define IDC_SWVOLUME_UP                 1133
#define IDC_BT_LIST1                    1133
#define IDC_VOLUME_EDIT7                1134
#define IDC_SWVOLUME_STATIC2            1134
#define IDC_BT_CHECK                    1134
#define IDC_VOLUME_STATIC8              1135
#define IDC_SWVOLUME_CHECK2             1135
#define IDC_BT_EDIT1                    1135
#define IDC_VOLUME_SLIDER8              1136
#define IDC_SWVOLUME_SLIDER2            1136
#define IDC_BT_PCM_MUTE                 1136
#define IDC_VOLUME_EDIT8                1137
#define IDC_SWVOLUME_EDIT2              1137
#define IDC_BT_CLS                      1137
#define IDC_VOLUME_STATIC9              1138
#define IDC_SWVOLUME_STATIC3            1138
#define IDC_BT_PCM_UNMUTE               1138
#define IDC_VOLUME_SLIDER9              1139
#define IDC_SWVOLUME_CHECK3             1139
#define IDC_BT_CTP_MUTE                 1139
#define IDC_VOLUME_EDIT9                1140
#define IDC_SWVOLUME_SLIDER3            1140
#define IDC_BT_CTP_UNMUTE               1140
#define IDC_SWVOLUME_EDIT3              1141
#define IDC_AV_PLAY                     1141
#define IDC_SWVOLUME_EDIT4              1142
#define IDC_AV_STATIC1                  1142
#define IDC_SWVOLUME_DOWN               1143
#define IDC_AV_CLS                      1143
#define IDC_SWVOLUME_UP2                1144
#define IDC_AV_DUMP                     1144
#define IDC_SWVOLUME_DOWN2              1145
#define IDC_AV_EDIT1                    1145
#define IDC_EQ_VIDEO                    1146
#define IDC_AV_LIST1                    1146
#define IDC_AV_STOP                     1147
#define IDM_FILE_EXIT                   40002
#define IDM_HELP_ABOUT                  40003
#define IDM_HW_VERSION                  40004
#define IDM_FLASH_CONTENT               40005
#define IDM_TOUCH                       40006
#define IDM_BACKLIGHT                   40007
#define IDM_HARDDRIVE                   40008
#define IDM_GPS                         40009
#define IDM_VDBG                        40010
#define IDM_FILE_REBOOT                 40011
#define IDM_FILE_REIBOOT                40012
#define IDM_SDMMC                       40013
#define IDM_AUTO_SUSPEND                40014
#define IDM_THREAD_TEST                 40015
#define IDM_ECHO                        40016
#define IDM_PERFORMANCE_COUNT           40017
#define IDM_AUDIO                       40018
#define IDM_VOLUME                      40019
#define IDM_EQ                          40020
#define IDM_SWVOLUME                    40021
#define IDM_BT                          40022
#define IDM_OSCAPTURE_RUN               40023
#define IDM_TRIGGER_OSCAPTURE           40024
#define IDM_AV                          40025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40026
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
