/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: Reno_Icon_20_GPS_Off
* Dimensions:  20 * 20
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsReno_Icon_20_GPS_Off[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalReno_Icon_20_GPS_Off = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsReno_Icon_20_GPS_Off[0]
};

static GUI_CONST_STORAGE unsigned char acReno_Icon_20_GPS_Off[] = {
  XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXX__, ________, XXXX____,
  XXXX__XX, XXXX____, _XXX____,
  XXX__XXX, XXX_____, __XX____,
  XXX__XXX, XXX_____, ___X____,
  XX_XX_XX, XXX_____, __XX____,
  XX_XXX_X, XXX_____, __XX____,
  X_XXXXX_, ________, X_XX____,
  X_XXXXX_, ____XXXX, X_XX____,
  X_XXXXX_, ____XXXX, X_XX____,
  X_XXXXX_, ____XXXX, X_XX____,
  X_X_____, ____XXXX, X_XX____,
  XX______, XXXX_XXX, X_XX____,
  X_______, XXXXX_XX, X_XX____,
  X_______, XXXXXX_X, _XXX____,
  X_______, XXXXXXX_, XXXX____,
  XX_____X, XXXXX__X, XXXX____,
  XXX_____, _____XXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXX____
};

GUI_CONST_STORAGE GUI_BITMAP bmReno_Icon_20_GPS_Off = {
  20, /* XSize */
  20, /* YSize */
  3, /* BytesPerLine */
  1, /* BitsPerPixel */
  acReno_Icon_20_GPS_Off,  /* Pointer to picture data (indices) */
  &PalReno_Icon_20_GPS_Off  /* Pointer to palette */
};

/* *** End of file *** */
